[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["YangHoo! <PolymagicYang@protonmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
fastapi = "0.108.0.*"
uvicorn = "0.25.0.*"
sqlalchemy = "2.0.25.*"
psycopg2 = "2.9.9.*"
