apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-api-deployment
  labels:
    app: todolist-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todolist-api
  template:
    metadata:
      labels:
        app: todolist-api
    spec:
      containers:
      - name: todolist-backend
        image: yanghoo/todolist-backend:v1.0.2
        ports:
        - containerPort: 2333 
        envFrom:
          - configMapRef:
              name: todolist-api-config
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD