apiVersion: app/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:13.1-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envForm:
          - ConfigMapRef:
            name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueForm:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: postgredb
    volumes:
      - name: postgredb
        PersistentVolumeClaim:
          claimName: postgres-pv-claim
