apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }} 
spec:
  selector:
    matchLabels:
      app: todolist-db
  template:
    metadata:
      labels:
        app: todolist-db
    spec:
      containers:
      - name: {{ .Values.name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"  
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        portssql:
          - containerPort: 5432
            name: db
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/postgres/data
            name: {{ .Values.name }} 
      volumes:
        - name: {{ .Values.name }} 
          persistentVolumeClaim:
            claimName: postgres-pv-claim
