kind: PersistentVolume
apiVersion: v1
metadata:
  name: psql-pv-volume
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/postgres/data"
