apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-guest
  namespace: default
subjects:
- kind: User
  name: guest 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: guest 
  apiGroup: rbac.authorization.k8s.io
