# deny all incomming connections by default.
{{ if eq .Values.deny.all "yes" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{ end }}
