apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.configmap.data.db_host }}
  DB_PORT: {{ .Values.configmap.data.db_port }} 