apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.apiConfigmap.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.apiConfigmap.data.db_host }}
  DB_PORT: "{{ .Values.apiConfigmap.data.db_port }}"