apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }} 
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }} 
  {{- end }}
  selector:
    matchLabels:
      app: todolist-api
  template:
    metadata:
      labels:
        app: todolist-api
    spec:
      containers:
      - name: {{ .Values.image.name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 2333 
        envFrom:
          - configMapRef:
              name: {{ .Values.apiConfigmap.name }} 
          - configMapRef:
              name: {{ .Values.dbConfigmap.name }} 
        env:
          - name: {{ .Values.dbSecret.name }} 
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dbSecret.data.name }} 
                key: {{ .Values.dbSecret.data.key }} 
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
