apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guest-bind
  namespace: intern
subjects:
- kind: User
  name: intern 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: intern
  apiGroup: rbac.authorization.k8s.io
