apiVersion: v1
kind: Namespace
metadata:
  name: certs

---

apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: certs 
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlRENDQXg2Z0F3SUJBZ0lVQTNCc2lXUlkrK0UyZTJzWHBNNSs5UDdxL1pNd0NnWUlLb1pJemowRUF3SXcKZ2FreEN6QUpCZ05WQkFZVEFrNU1NUll3RkFZRFZRUUlEQTFPYjNKMGFDQkliMnhzWVc1a01SSXdFQVlEVlFRSApEQWxCYlhOMFpYSmtZVzB4RlRBVEJnTlZCQW9NREZaVklFRnRjM1JsY21SaGJURWJNQmtHQTFVRUN3d1NSbUZqCmRXeDBlU0J2WmlCVFkybGxibU5sTVJVd0V3WURWUVFEREF4YWFHbDVZVzVuSUZkaGJtY3hJekFoQmdrcWhraUcKOXcwQkNRRVdGSGwzWVRJeU4wQnpkSFZrWlc1MExuWjFMbTVzTUI0WERUSTBNREV5TURBeU1qZzBNMW9YRFRNMApNREV4TnpBeU1qZzBNMW93Z2FreEN6QUpCZ05WQkFZVEFrNU1NUll3RkFZRFZRUUlEQTFPYjNKMGFDQkliMnhzCllXNWtNUkl3RUFZRFZRUUhEQWxCYlhOMFpYSmtZVzB4RlRBVEJnTlZCQW9NREZaVklFRnRjM1JsY21SaGJURWIKTUJrR0ExVUVDd3dTUm1GamRXeDBlU0J2WmlCVFkybGxibU5sTVJVd0V3WURWUVFEREF4YWFHbDVZVzVuSUZkaApibWN4SXpBaEJna3Foa2lHOXcwQkNRRVdGSGwzWVRJeU4wQnpkSFZrWlc1MExuWjFMbTVzTUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRXFaRXBQZHlJd2o4ZHU4VnFvOERnVTdpTXZza2llT3FhRnUyZDk0RlcKamMzQm5oZ0llVjIwQThabzNxUXVSYXkwRTFlZFRZck9rYi9kcFNqUDhiQzZTcU9DQVNBd2dnRWNNQjBHQTFVZApEZ1FXQkJRcHpzMC95Y3JJNEJtSlVUKzd5L0c1SUxHOGVUQ0I2UVlEVlIwakJJSGhNSUhlZ0JRcHpzMC95Y3JJCjRCbUpVVCs3eS9HNUlMRzhlYUdCcjZTQnJEQ0JxVEVMTUFrR0ExVUVCaE1DVGt3eEZqQVVCZ05WQkFnTURVNXYKY25Sb0lFaHZiR3hoYm1ReEVqQVFCZ05WQkFjTUNVRnRjM1JsY21SaGJURVZNQk1HQTFVRUNnd01WbFVnUVcxegpkR1Z5WkdGdE1Sc3dHUVlEVlFRTERCSkdZV04xYkhSNUlHOW1JRk5qYVdWdVkyVXhGVEFUQmdOVkJBTU1ERnBvCmFYbGhibWNnVjJGdVp6RWpNQ0VHQ1NxR1NJYjNEUUVKQVJZVWVYZGhNakkzUUhOMGRXUmxiblF1ZG5VdWJteUMKRkFOd2JJbGtXUHZoTm50ckY2VE9mdlQrNnYyVE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWdaY1pneW5VWlN0VlRJQU0wOVZ4cnViUE9EWndIcHNrOGo2SXNGd3crd3NFQ0lRQ1ZXZ2FsCkRWSFA3QW5Qd0hjckJuMTFuZTRYanFZMzlLWHVsQS9DRmZYU0VnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUpTdEJkakxZK2xkQnl1TyszQzRvRklVamRRdXpVcnVnNUNtRExtZUNkRlNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFcVpFcFBkeUl3ajhkdThWcW84RGdVN2lNdnNraWVPcWFGdTJkOTRGV2pjM0JuaGdJZVYyMApBOFpvM3FRdVJheTBFMWVkVFlyT2tiL2RwU2pQOGJDNlNnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo= 

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: certs 
spec:
  ca:
    secretName: ca-key-pair